
DROP TABLE IF EXISTS ybox_bars;

CREATE TABLE ybox_bars (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	slug VARCHAR(32) NOT NULL UNIQUE,
	name VARCHAR(64) NOT NULL,
	address VARCHAR(128) NOT NULL,
	lat DOUBLE(12,9) NOT NULL DEFAULT 0.0,
	lng DOUBLE(12,9) NOT NULL DEFAULT 0.0,
	active ENUM('true','false') DEFAULT 'false'
);

